[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "propertyware-automation"
version = "0.1.1"
description = "Propertyware 3-day Notice automation (packaged UI + CLI)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "loguru>=0.7",
  "python-dotenv>=1.0",
  "playwright>=1.45",
  "python-docx>=1.1",
  "python-dateutil>=2.9",
  "streamlit>=1.35",
]

[project.scripts]
pw-auto = "pw_auto.orchestrator:cli"
pw-ui   = "pw_auto.launch_ui:main"

# 🔒 Restrict package discovery to only pw_auto
[tool.setuptools.packages.find]
where = ["."]
include = ["pw_auto_]()
